spring:
  application:
    name: api-gateway-web
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    microserviceMain:
      path: /microservice/**
      serviceId: microservice-main
      strip-prefix: false
    microserviceSeconf:
      path: /microserviceSecond/**
      serviceId: microservice-second
      strip-prefix: false
