spring:
  application:
    name: api-gateway-web
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
